services:
  dev:
    image: lunarzdev/mhseals-dev:nvidia
    build:
      args:
        TARGET_PLATFORM: nvidia
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
    volumes:
      - zed_resources:/usr/local/zed/resources 
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
  sitl:
    image: lunarzdev/mhseals-sitl:nvidia
volumes:
  zed_resources: