services:
  roboboat:
    image: lunarzdev/mhseals-dev-windows
    pull_policy: missing
    environment:
      DISPLAY: host.docker.internal:0
    volumes: []
  sitl:
    image: lunarzdev/mhseals-sitl-windows
    pull_policy: missing
    environment:
      DISPLAY: host.docker.internal:0
    volumes:
      - ./boat.param:/param/boat.param:ro