services:
  roboboat:
    environment:
      DISPLAY: host.docker.internal:0
    volumes: []
  sitl:
    environment:
      DISPLAY: host.docker.internal:0
    volumes:
      - ./boat.param:/param/boat.param:ro