services:
  dev:
    image: lunarzdev/mhseals-sitl:mac
    environment:
      DISPLAY: host.docker.internal:0
    volumes: []
  sitl:
    image: lunarzdev/mhseals-sitl:mac
    environment:
      DISPLAY: host.docker.internal:0
    volumes:
      - ./boat.param:/param/boat.param:ro